"""Diccionario autogenerado para Sweetviz"""

SWEETVIZ_LABELS = {
    "ID1": "ID1 - Año",
    "id1": "ID1 - Año",
    "hv022": "HV022 - Estrato de la muestra",
    "HV022": "HV022 - Estrato de la muestra",
    "codccpp": "CODCCPP - Código de centro poblado (mayúscula)",
    "CODCCPP": "CODCCPP - Código de centro poblado (mayúscula)",
    "nomccpp": "NOMCCPP - Nombre de centro poblado (mayúscula)",
    "NOMCCPP": "NOMCCPP - Nombre de centro poblado (mayúscula)",
    "long_ccpp": "long_ccpp - Longitud geográfica",
    "LONG_CCPP": "long_ccpp - Longitud geográfica",
    "lat_ccpp": "lat_ccpp - Latitud geográfica",
    "LAT_CCPP": "lat_ccpp - Latitud geográfica",
    "ubigeo": "UBIGEO - Ubigeo (Código de Ubicación Geográfica)",
    "UBIGEO": "UBIGEO - Ubigeo (Código de Ubicación Geográfica)",
    "nconglome": "NCONGLOME - Número de Conglomerado (mayúscula)",
    "NCONGLOME": "NCONGLOME - Número de Conglomerado (mayúscula)",
    "NCONGLOME1": "NCONGLOME1 - Número de Conglomerado",
    "nconglome1": "NCONGLOME1 - Número de Conglomerado",
    "HV024": "HV024 - Región",
    "hv024": "HV024 - Región",
    "HV025": "HV025 - Área de residencia",
    "hv025": "HV025 - Área de residencia",
    "HV026": "HV026 - Place of residence (Lugar de residencia)",
    "hv026": "HV026 - Place of residence (Lugar de residencia)",
    "HV015": "HV015 - Resultado de la entrevista",
    "hv015": "HV015 - Resultado de la entrevista",
    "HV003": "HV003 - Número de línea del encuestado",
    "hv003": "HV003 - Número de línea del encuestado",
    "HV004": "HV004 - Unidad última de muestreo (UPM)",
    "hv004": "HV004 - Unidad última de muestreo (UPM)",
    "HV005": "hv005 - Factor de ponderación (minúscula)",
    "hv005": "hv005 - Factor de ponderación (minúscula)",
    "HV008": "HV008 - Fecha de entrevista (CMC)",
    "hv008": "HV008 - Fecha de entrevista (CMC)",
    "HV009": "HV009 - Total de personas en el hogar",
    "hv009": "HV009 - Total de personas en el hogar",
    "HV010": "HV010 - Mujeres elegibles en el hogar",
    "hv010": "HV010 - Mujeres elegibles en el hogar",
    "HV011": "HV011 - Hombres elegibles en el hogar",
    "hv011": "HV011 - Hombres elegibles en el hogar",
    "HV012": "HV012 - Miembros habituales (De jure)",
    "hv012": "HV012 - Miembros habituales (De jure)",
    "HV013": "HV013 - Miembros presentes (De facto)",
    "hv013": "HV013 - Miembros presentes (De facto)",
    "HV014": "HV014 - Niños menores de 5 años",
    "hv014": "HV014 - Niños menores de 5 años",
    "HV021": "HV021 - Unidad Primaria de Muestreo (UPM)",
    "hv021": "HV021 - Unidad Primaria de Muestreo (UPM)",
    "HV035": "HV035 - Niños elegibles para antropometría",
    "hv035": "HV035 - Niños elegibles para antropometría",
    "HV040": "HV040 - Cluster altitude in meters (Altitud del conglomerado en metros)",
    "hv040": "HV040 - Cluster altitude in meters (Altitud del conglomerado en metros)",
    "HV041": "HV041 - Adultos/Mujeres medidas (Antropometría)",
    "hv041": "HV041 - Adultos/Mujeres medidas (Antropometría)",
    "longitudx": "LONGITUDX - Longitud del conglomerado (mayúscula)",
    "LONGITUDX": "LONGITUDX - Longitud del conglomerado (mayúscula)",
    "latitudy": "LATITUDY - Latitud del conglomerado (mayúscula)",
    "LATITUDY": "LATITUDY - Latitud del conglomerado (mayúscula)",
    "HHID": "HHID - Identificación del hogar / Cuestionario",
    "hhid": "HHID - Identificación del hogar / Cuestionario",
    "HV000": "HV000 - Código del país y fase",
    "hv000": "HV000 - Código del país y fase",
    "HV002A": "HV002A - Número de hogar (Vivienda)",
    "hv002a": "HV002A - Número de hogar (Vivienda)",
    "HV001": "HV001 - Número de conglomerado",
    "hv001": "HV001 - Número de conglomerado",
    "HV002": "HV002 - Número de vivienda/hogar",
    "hv002": "HV002 - Número de vivienda/hogar",
    "HVIDX": "HVIDX - Número de orden del individuo",
    "hvidx": "HVIDX - Número de orden del individuo",
    "HV101": "HV101 - Parentesco con jefe de hogar",
    "hv101": "HV101 - Parentesco con jefe de hogar",
    "HV102": "HV102 - Residente habitual",
    "hv102": "HV102 - Residente habitual",
    "HV103": "HV103 - ¿Durmió aquí anoche?",
    "hv103": "HV103 - ¿Durmió aquí anoche?",
    "HV104": "HV104 - Sexo",
    "hv104": "HV104 - Sexo",
    "HV105": "HV105 - Edad",
    "hv105": "HV105 - Edad",
    "HV106": "HV106 - Nivel de estudios más alto",
    "hv106": "HV106 - Nivel de estudios más alto",
    "HV107": "HV107 - Grado o año más alto aprobado",
    "hv107": "HV107 - Grado o año más alto aprobado",
    "HV108": "HV108 - Número de años de estudio",
    "hv108": "HV108 - Número de años de estudio",
    "HV109": "HV109 - Nivel educativo alcanzado",
    "hv109": "HV109 - Nivel educativo alcanzado",
    "HV110": "HV110 - Asiste a escuela",
    "hv110": "HV110 - Asiste a escuela",
    "HV111": "HV111 - ¿Está viva la madre natural?",
    "hv111": "HV111 - ¿Está viva la madre natural?",
    "HV112": "HV112 - ID de la madre en el hogar",
    "hv112": "HV112 - ID de la madre en el hogar",
    "HV113": "HV113 - ¿Está vivo el padre natural?",
    "hv113": "HV113 - ¿Está vivo el padre natural?",
    "HV114": "HV114 - Número de orden del padre",
    "hv114": "HV114 - Número de orden del padre",
    "HV115": "HV115 - Estado civil o conyugal",
    "hv115": "HV115 - Estado civil o conyugal",
    "HV120": "HV120 - Niños elegibles para medición",
    "hv120": "HV120 - Niños elegibles para medición",
    "HV121": "HV121 - Asistió a escuela este año",
    "hv121": "HV121 - Asistió a escuela este año",
    "HV122": "HV122 - Nivel asiste/matriculado actual",
    "hv122": "HV122 - Nivel asiste/matriculado actual",
    "HV124": "HV124 - Años de estudio matriculado",
    "hv124": "HV124 - Años de estudio matriculado",
    "HV125": "HV125 - Estuvo matriculado año pasado",
    "hv125": "HV125 - Estuvo matriculado año pasado",
    "HV126": "HV126 - Nivel matriculado año pasado",
    "hv126": "HV126 - Nivel matriculado año pasado",
    "HV128": "HV128 - Años de estudio año pasado",
    "hv128": "HV128 - Años de estudio año pasado",
    "SH2201": "SH2201 - Water to drink is available the one whole day",
    "sh2201": "SH2201 - Water to drink is available the one whole day",
    "HV201": "HV201 - Source of drinking water (Fuente principal)",
    "hv201": "HV201 - Source of drinking water (Fuente principal)",
    "HV204": "HV204 - Time to get to water source (Tiempo de viaje a fuente)",
    "hv204": "HV204 - Time to get to water source (Tiempo de viaje a fuente)",
    "HV205": "HV205 - Type of toilet facility (Tipo de servicio higiénico)",
    "hv205": "HV205 - Type of toilet facility (Tipo de servicio higiénico)",
    "HV225": "HV225 - Share toilet with other households (Comparte servicio higiénico)",
    "hv225": "HV225 - Share toilet with other households (Comparte servicio higiénico)",
    "HV236": "HV236 - Person fetching water (Persona que recoge agua)",
    "hv236": "HV236 - Person fetching water (Persona que recoge agua)",
    "HV237": "HV237 - Anything done to water to make safe to drink (Tratamiento del agua)",
    "hv237": "HV237 - Anything done to water to make safe to drink (Tratamiento del agua)",
    "HV237A": "HV237A - Water usually treated by: boil (Tratamiento de agua: hervir)",
    "hv237a": "HV237A - Water usually treated by: boil (Tratamiento de agua: hervir)",
    "HV237B": "HV237B - Water usually treated by: add bleach/chlorine (Añadir lejía o cloro)",
    "hv237b": "HV237B - Water usually treated by: add bleach/chlorine (Añadir lejía o cloro)",
    "HV237C": "HV237C - Water usually treated by: strain through a cloth (Filtrar por paño)",
    "hv237c": "HV237C - Water usually treated by: strain through a cloth (Filtrar por paño)",
    "HV237D": "HV237D - Water usually treated by: use water filter (Usar filtro de agua)",
    "hv237d": "HV237D - Water usually treated by: use water filter (Usar filtro de agua)",
    "HV237E": "HV237E - Water usually treated by: solar disinfection (Desinfección solar)",
    "hv237e": "HV237E - Water usually treated by: solar disinfection (Desinfección solar)",
    "HV237F": "HV237F - Water usually treated by: let it stand and settle (Dejar reposar)",
    "hv237f": "HV237F - Water usually treated by: let it stand and settle (Dejar reposar)",
    "HV237G": "HV237G - Water usually treated by: CS - packed water (Agua embotellada)",
    "hv237g": "HV237G - Water usually treated by: CS - packed water (Agua embotellada)",
    "HV237X": "HV237X - Water usually treated by: other (Tratamiento de agua: otros)",
    "hv237x": "HV237X - Water usually treated by: other (Tratamiento de agua: otros)",
    "HV238": "HV238 - Number of households sharing toilet (Número de hogares compartiendo baño)",
    "hv238": "HV238 - Number of households sharing toilet (Número de hogares compartiendo baño)",
    "SH2202": "SH2202 - Last 2 weeks was water discontinued for a day or more",
    "sh2202": "SH2202 - Last 2 weeks was water discontinued for a day or more",
    "SH2203": "SH2203 - Other source of water when it wasn't availalble",
    "sh2203": "SH2203 - Other source of water when it wasn't availalble",
    "SH2204": "SH2204 - Do you store the water to drink",
    "sh2204": "SH2204 - Do you store the water to drink",
    "SH2208": "SH2208 - Does household pays for water service",
    "sh2208": "SH2208 - Does household pays for water service",
    "SH2209": "SH2209 - Agency that collects water fees",
    "sh2209": "SH2209 - Agency that collects water fees",
    "SH2210": "SH2210 - How often pays for water service",
    "sh2210": "SH2210 - How often pays for water service",
    "SH2401": "SH2401 - Where is the bathroom or latrine located",
    "sh2401": "SH2401 - Where is the bathroom or latrine located",
    "SH2406": "SH2406 - How often is the bathroom or latrine cleaned",
    "sh2406": "SH2406 - How often is the bathroom or latrine cleaned",
    "SH2412": "SH2412 - Where does household throw away the garbage",
    "sh2412": "SH2412 - Where does household throw away the garbage",
    "SH2413": "SH2413 - How often is garbage picked up",
    "sh2413": "SH2413 - How often is garbage picked up",
    "SH2414": "SH2414 - Before disposing of garbage where it is stored",
    "sh2414": "SH2414 - Before disposing of garbage where it is stored",
    "SH32": "SH32 - Agua potable esta disponible el día entero",
    "sh32": "SH32 - Agua potable esta disponible el día entero",
    "SH33": "SH33 - En las 2 últimas semanas el agua fue suspendida por un día o más",
    "sh33": "SH33 - En las 2 últimas semanas el agua fue suspendida por un día o más",
    "SH37": "SH37 - Almacena el agua para beber",
    "sh37": "SH37 - Almacena el agua para beber",
    "SH39": "SH39 - El hogar paga por el servicio de agua",
    "sh39": "SH39 - El hogar paga por el servicio de agua",
    "SH40": "SH40 - Agencia que recibe los cobros por el agua",
    "sh40": "SH40 - Agencia que recibe los cobros por el agua",
    "SH41": "SH41 - Con que frecuencia paga por el servicio de agua",
    "sh41": "SH41 - Con que frecuencia paga por el servicio de agua",
    "SH42": "SH42 - Water to drink is available the one whole day (Agua disponible todo el día)",
    "sh42": "SH42 - Water to drink is available the one whole day (Agua disponible todo el día)",
    "SH43": "SH43 - Last 2 weeks was water discontinued for a day or more (Agua suspendida 2 últimas semanas)",
    "sh43": "SH43 - Last 2 weeks was water discontinued for a day or more (Agua suspendida 2 últimas semanas)",
    "SH46": "SH46 - Cada cuánto limpia el baño o letrina",
    "sh46": "SH46 - Cada cuánto limpia el baño o letrina",
    "SH48": "SH48 - Do you store the water to drink (Almacena el agua para beber)",
    "sh48": "SH48 - Do you store the water to drink (Almacena el agua para beber)",
    "SH49": "SH49 - Has a container or packet (Tipo de envase o recipiente)",
    "sh49": "SH49 - Has a container or packet (Tipo de envase o recipiente)",
    "SH50": "SH50 - Use lid (¿Lo usa con tapa?)",
    "sh50": "SH50 - Use lid (¿Lo usa con tapa?)",
    "SH51": "SH51 - Do you payment for water (¿Pago por el agua?)",
    "sh51": "SH51 - Do you payment for water (¿Pago por el agua?)",
    "SH52": "SH52 - Institution for payment water (Institución de pago de agua)",
    "sh52": "SH52 - Institution for payment water (Institución de pago de agua)",
    "SH56": "SH56 - How often is the bathroom or latrine cleaned (Con qué frecuencia se limpia el baño)",
    "sh56": "SH56 - How often is the bathroom or latrine cleaned (Con qué frecuencia se limpia el baño)",
    "SH58": "SH58 - Where does household throw away the garbage (Dónde tira la basura)",
    "sh58": "SH58 - Where does household throw away the garbage (Dónde tira la basura)",
    "SH59": "SH59 - How often is garbage picked up (Con qué frecuencia se recoge la basura)",
    "sh59": "SH59 - How often is garbage picked up (Con qué frecuencia se recoge la basura)",
    "SH60": "SH60 - Before disposing of garbage where it is stored (Antes de desechar la basura donde se almacena)",
    "sh60": "SH60 - Before disposing of garbage where it is stored (Antes de desechar la basura donde se almacena)",
    "SH110": "SH110 - Test de cloro",
    "sh110": "SH110 - Test de cloro",
    "SH127": "SH127 - Test de cloro",
    "sh127": "SH127 - Test de cloro",
    "SH227": "SH227 - Chlorine test (Prueba de cloro)",
    "sh227": "SH227 - Chlorine test (Prueba de cloro)",
    "QH227A": "QH227A - La muestra fue tomada por:",
    "qh227a": "QH227A - La muestra fue tomada por:",
    "QH227B": "QH227B - La muestra del agua se extrajo del:",
    "qh227b": "QH227B - La muestra del agua se extrajo del:",
    "SH25F": "SH25F - Has a computer",
    "sh25f": "SH25F - Has a computer",
    "SH25H": "SH25H - Has internet access at home",
    "sh25h": "SH25H - Has internet access at home",
    "SH26A": "SH26A - Number of rooms in the household",
    "sh26a": "SH26A - Number of rooms in the household",
    "SH2601": "SH2601 - Use other type of fuel for cooking",
    "sh2601": "SH2601 - Use other type of fuel for cooking",
    "SH2602": "SH2602 - Type of other fuel used for cooking",
    "sh2602": "SH2602 - Type of other fuel used for cooking",
    "SH2604": "SH2604 - Does household buys fuel for cooking",
    "sh2604": "SH2604 - Does household buys fuel for cooking",
    "SH2609": "SH2609 - Type of light used by household",
    "sh2609": "SH2609 - Type of light used by household",
    "SH27CA": "SH27CA - Dwelling has windows",
    "sh27ca": "SH27CA - Dwelling has windows",
    "SH27CB": "SH27CB - Windows with glass",
    "sh27cb": "SH27CB - Windows with glass",
    "SH27CC": "SH27CC - Wood windows",
    "sh27cc": "SH27CC - Wood windows",
    "SH27CD": "SH27CD - Windows with screens",
    "sh27cd": "SH27CD - Windows with screens",
    "SH27CE": "SH27CE - Windows with curtains/blinds",
    "sh27ce": "SH27CE - Windows with curtains/blinds",
    "SH2801": "SH2801 - Any household member rents land for agricultural use",
    "sh2801": "SH2801 - Any household member rents land for agricultural use",
    "SH28D": "SH28D - Any other transportation type (horses, peque-peque, etc)",
    "sh28d": "SH28D - Any other transportation type (horses, peque-peque, etc)",
    "SH51A": "SH51A - Tiene sofá",
    "sh51a": "SH51A - Tiene sofá",
    "HV207": "HV207 - Has radio (Tiene radio)",
    "hv207": "HV207 - Has radio (Tiene radio)",
    "HV208": "HV208 - Has television (Tiene televisión)",
    "hv208": "HV208 - Has television (Tiene televisión)",
    "HV209": "HV209 - Has refrigerator (Tiene refrigerador)",
    "hv209": "HV209 - Has refrigerator (Tiene refrigerador)",
    "HV210": "HV210 - Has bicycle (Tiene bicicleta)",
    "hv210": "HV210 - Has bicycle (Tiene bicicleta)",
    "HV211": "HV211 - Has motorcycle/scooter (Tiene motocicleta)",
    "hv211": "HV211 - Has motorcycle/scooter (Tiene motocicleta)",
    "HV212": "HV212 - Has car/truck (Tiene carro o camión)",
    "hv212": "HV212 - Has car/truck (Tiene carro o camión)",
    "HV213": "HV213 - Main floor material (Material predominante en el piso)",
    "hv213": "HV213 - Main floor material (Material predominante en el piso)",
    "HV214": "HV214 - Main wall material (Material predominante en la pared)",
    "hv214": "HV214 - Main wall material (Material predominante en la pared)",
    "HV215": "HV215 - Main roof material (Material predominante en el techo)",
    "hv215": "HV215 - Main roof material (Material predominante en el techo)",
    "HV216": "HV216 - Rooms used for sleeping (Habitaciones para dormir)",
    "hv216": "HV216 - Rooms used for sleeping (Habitaciones para dormir)",
    "HV221": "HV221 - Has telephone (Tiene teléfono)",
    "hv221": "HV221 - Has telephone (Tiene teléfono)",
    "HV226": "HV226 - Type of cooking fuel (Tipo de combustible para cocinar)",
    "hv226": "HV226 - Type of cooking fuel (Tipo de combustible para cocinar)",
    "HV240": "HV240 - Household has a chimney, hood or neither (Tiene chimenea o campana)",
    "hv240": "HV240 - Household has a chimney, hood or neither (Tiene chimenea o campana)",
    "HV242": "HV242 - Household has separate room used as kitchen (Cuarto separado para cocinar)",
    "hv242": "HV242 - Household has separate room used as kitchen (Cuarto separado para cocinar)",
    "HV243A": "HV243A - Has a mobile telephone (Tiene celular)",
    "hv243a": "HV243A - Has a mobile telephone (Tiene celular)",
    "HV243B": "HV243B - Has a watch (Tiene reloj)",
    "hv243b": "HV243B - Has a watch (Tiene reloj)",
    "HV243C": "HV243C - Has an animal-drawn cart (Tiene carreta jalada por animales)",
    "hv243c": "HV243C - Has an animal-drawn cart (Tiene carreta jalada por animales)",
    "HV243D": "HV243D - Has a boat with a motor (Tiene bote a motor)",
    "hv243d": "HV243D - Has a boat with a motor (Tiene bote a motor)",
    "SH51B": "SH51B - Tiene vitrina/aparado",
    "sh51b": "SH51B - Tiene vitrina/aparado",
    "SH51C": "SH51C - Tiene repostero",
    "sh51c": "SH51C - Tiene repostero",
    "SH51D": "SH51D - Tiene cómoda/ropero",
    "sh51d": "SH51D - Tiene cómoda/ropero",
    "SH51E": "SH51E - Tiene reloj de pared",
    "sh51e": "SH51E - Tiene reloj de pared",
    "SH51J": "SH51J - Tiene televisión por cable",
    "sh51j": "SH51J - Tiene televisión por cable",
    "SH51K": "SH51K - Tiene licuadora",
    "sh51k": "SH51K - Tiene licuadora",
    "SH51L": "SH51L - Tiene cocina a gas",
    "sh51l": "SH51L - Tiene cocina a gas",
    "SH51M": "SH51M - Tiene cocina a kerosene",
    "sh51m": "SH51M - Tiene cocina a kerosene",
    "SH51N": "SH51N - Tiene microondas",
    "sh51n": "SH51N - Tiene microondas",
    "SH51O": "SH51O - Tiene lavadora",
    "sh51o": "SH51O - Tiene lavadora",
    "SH51P": "SH51P - Tiene computadora",
    "sh51p": "SH51P - Tiene computadora",
    "SH51Q": "SH51Q - Tiene acceso a Internet en casa",
    "sh51q": "SH51Q - Tiene acceso a Internet en casa",
    "SH51R": "SH51R - Tiene bomba de agua",
    "sh51r": "SH51R - Tiene bomba de agua",
    "SH51S": "SH51S - Tiene generador de electricidad",
    "sh51s": "SH51S - Tiene generador de electricidad",
    "SH53": "SH53 - Usa otro tipo de combustible para cocinar",
    "sh53": "SH53 - Usa otro tipo de combustible para cocinar",
    "SH54": "SH54 - Tipo de otro combustible usado para cocinar",
    "sh54": "SH54 - Tipo de otro combustible usado para cocinar",
    "SH61": "SH61 - Número de habitaciones en el hogar",
    "sh61": "SH61 - Número de habitaciones en el hogar",
    "SH61A": "SH61A - Has a sofa (¿Tiene sofá?)",
    "sh61a": "SH61A - Has a sofa (¿Tiene sofá?)",
    "SH61B": "SH61B - Has a cabinet (¿Tiene vitrina/aparador?)",
    "sh61b": "SH61B - Has a cabinet (¿Tiene vitrina/aparador?)",
    "SH61C": "SH61C - Has a shelf (¿Tiene repostero?)",
    "sh61c": "SH61C - Has a shelf (¿Tiene repostero?)",
    "SH61D": "SH61D - Has a wardrobe (¿Tiene cómoda/ropero?)",
    "sh61d": "SH61D - Has a wardrobe (¿Tiene cómoda/ropero?)",
    "SH61E": "SH61E - Has a wall's clock (¿Tiene reloj de pared?)",
    "sh61e": "SH61E - Has a wall's clock (¿Tiene reloj de pared?)",
    "SH61J": "SH61J - Has a cable television (¿Tiene televisión por cable?)",
    "sh61j": "SH61J - Has a cable television (¿Tiene televisión por cable?)",
    "SH61K": "SH61K - Has a blender (¿Tiene licuadora?)",
    "sh61k": "SH61K - Has a blender (¿Tiene licuadora?)",
    "SH61L": "SH61L - Has a gas cooker (¿Tiene cocina de gas?)",
    "sh61l": "SH61L - Has a gas cooker (¿Tiene cocina de gas?)",
    "SH61M": "SH61M - Has a kerosen cooker (¿Tiene cocina de kerosene?)",
    "sh61m": "SH61M - Has a kerosen cooker (¿Tiene cocina de kerosene?)",
    "SH61N": "SH61N - Has a microwave (¿Tiene microondas?)",
    "sh61n": "SH61N - Has a microwave (¿Tiene microondas?)",
    "SH61O": "SH61O - Has a washing machine (¿Tiene lavadora?)",
    "sh61o": "SH61O - Has a washing machine (¿Tiene lavadora?)",
    "SH61P": "SH61P - Has a computer (¿Tiene computadora?)",
    "sh61p": "SH61P - Has a computer (¿Tiene computadora?)",
    "SH61Q": "SH61Q - Has internet access at home (¿Tiene acceso a Internet en casa?)",
    "sh61q": "SH61Q - Has internet access at home (¿Tiene acceso a Internet en casa?)",
    "SH61R": "SH61R - Has a water pump (¿Tiene bomba de agua?)",
    "sh61r": "SH61R - Has a water pump (¿Tiene bomba de agua?)",
    "SH61S": "SH61S - Has a electricity generator (¿Tiene generador de electricidad?)",
    "sh61s": "SH61S - Has a electricity generator (¿Tiene generador de electricidad?)",
    "SH63": "SH63 - Use other type of fuel for cooking (¿Utiliza otro tipo de combustible para cocinar?)",
    "sh63": "SH63 - Use other type of fuel for cooking (¿Utiliza otro tipo de combustible para cocinar?)",
    "SH64": "SH64 - Type of other fuel used for cooking (Otro tipo de combustible utilizado para cocinar)",
    "sh64": "SH64 - Type of other fuel used for cooking (Otro tipo de combustible utilizado para cocinar)",
    "SH66": "SH66 - Kitchen has a chimney (¿La cocina tiene una chimenea o un mecanismo para eliminar el humo?)",
    "sh66": "SH66 - Kitchen has a chimney (¿La cocina tiene una chimenea o un mecanismo para eliminar el humo?)",
    "SH67A": "SH67A - Vivienda tiene ventanas",
    "sh67a": "SH67A - Vivienda tiene ventanas",
    "SH67B": "SH67B - Ventanas con vidrios",
    "sh67b": "SH67B - Ventanas con vidrios",
    "SH67C": "SH67C - Ventanas de madera",
    "sh67c": "SH67C - Ventanas de madera",
    "SH67D": "SH67D - Ventanas mallas",
    "sh67d": "SH67D - Ventanas mallas",
    "SH67E": "SH67E - Ventanas con cortinas o persianas",
    "sh67e": "SH67E - Ventanas con cortinas o persianas",
    "SH68F": "SH68F - Otro medio de transporte (caballos, peque-peque, etc)",
    "sh68f": "SH68F - Otro medio de transporte (caballos, peque-peque, etc)",
    "SH69": "SH69 - Does household buys fuel for cooking (¿El hogar compra combustible para cocinar?)",
    "sh69": "SH69 - Does household buys fuel for cooking (¿El hogar compra combustible para cocinar?)",
    "SH70": "SH70 - Type of light used by household (¿Qué tipo de alumbrado utiliza el hogar?)",
    "sh70": "SH70 - Type of light used by household (¿Qué tipo de alumbrado utiliza el hogar?)",
    "SH71": "SH71 - Number of rooms in the household (Número de habitaciones en el hogar)",
    "sh71": "SH71 - Number of rooms in the household (Número de habitaciones en el hogar)",
    "SH76A": "SH76A - La vivienda tiene ventanas",
    "sh76a": "SH76A - La vivienda tiene ventanas",
    "SH76B": "SH76B - Ventanas con cristal",
    "sh76b": "SH76B - Ventanas con cristal",
    "SH76C": "SH76C - Ventanas de madera",
    "sh76c": "SH76C - Ventanas de madera",
    "SH76D": "SH76D - Windows with screens (Ventanas con malla)",
    "sh76d": "SH76D - Windows with screens (Ventanas con malla)",
    "SH76E": "SH76E - Windows with curtains/blinds (Ventanas con cortinas/persianas)",
    "sh76e": "SH76E - Windows with curtains/blinds (Ventanas con cortinas/persianas)",
    "SH77A": "SH77A - Vivienda tiene ventanas",
    "sh77a": "SH77A - Vivienda tiene ventanas",
    "SH77B": "SH77B - Ventanas con vidrios",
    "sh77b": "SH77B - Ventanas con vidrios",
    "SH77C": "SH77C - Ventanas de madera",
    "sh77c": "SH77C - Ventanas de madera",
    "SH77D": "SH77D - Ventanas mallas",
    "sh77d": "SH77D - Ventanas mallas",
    "SH77E": "SH77E - Ventanas con cortinas o persianas",
    "sh77e": "SH77E - Ventanas con cortinas o persianas",
    "SH77F": "SH77F - Any other transportation type (Otro tipo de transporte: caballos, peque-peque, etc)",
    "sh77f": "SH77F - Any other transportation type (Otro tipo de transporte: caballos, peque-peque, etc)",
    "SH78": "SH78 - Any household member rents land for agricultural use (¿Miembro del hogar es dueño de tierras agrícolas?)",
    "sh78": "SH78 - Any household member rents land for agricultural use (¿Miembro del hogar es dueño de tierras agrícolas?)",
    "SH78F": "SH78F - Otro medio de transporte (caballos, peque-peque, etc)",
    "sh78f": "SH78F - Otro medio de transporte (caballos, peque-peque, etc)",
    "SH107": "SH107 - Prueba de Yodo",
    "sh107": "SH107 - Prueba de Yodo",
    "SH124": "SH124 - Prueba de Yodo",
    "sh124": "SH124 - Prueba de Yodo",
    "SH224": "SH224 - Test of Iodine (Prueba de Yodo)",
    "sh224": "SH224 - Test of Iodine (Prueba de Yodo)",
    "HV234": "HV234 - Test salt for Iodine (Prueba de yodo para sal)",
    "hv234": "HV234 - Test salt for Iodine (Prueba de yodo para sal)",
    "hv270": "HV270 - Wealth index (Índice de riqueza)",
    "HV270": "HV270 - Wealth index (Índice de riqueza)",
    "hv271": "HV271 - Wealth index factor score (5 decimals) (Factor de puntuación del índice de riqueza)",
    "HV271": "HV271 - Wealth index factor score (5 decimals) (Factor de puntuación del índice de riqueza)",
    "HV206": "HV206 - Has electricity (Tiene electricidad)",
    "hv206": "HV206 - Has electricity (Tiene electricidad)",
    "HV217": "HV217 - Relationship structure (Estructura de relación)",
    "hv217": "HV217 - Relationship structure (Estructura de relación)",
    "HV219": "HV219 - Sex of head of household (Sexo del jefe del hogar)",
    "hv219": "HV219 - Sex of head of household (Sexo del jefe del hogar)",
    "HV220": "HV220 - Age of head of household (Edad del jefe del hogar)",
    "hv220": "HV220 - Age of head of household (Edad del jefe del hogar)",
    "SHTOTH": "SHTOTH - Households in dwelling (Hogares en la vivienda)",
    "shtoth": "SHTOTH - Households in dwelling (Hogares en la vivienda)",
    "SH2211": "SH2211 - Water bill average (1 decimal)",
    "sh2211": "SH2211 - Water bill average (1 decimal)",
    "SH28BB": "SH28BB - Hectares owned by household members (1 decimal)",
    "sh28bb": "SH28BB - Hectares owned by household members (1 decimal)",
    "SH79": "SH79 - Hectares owned by household members (Cuantas hectareas)",
    "sh79": "SH79 - Hectares owned by household members (Cuantas hectareas)",
    "SH80": "SH80 - Hectáreas de propiedad de miembros del hogar (1 decimal)",
    "sh80": "SH80 - Hectáreas de propiedad de miembros del hogar (1 decimal)",
    "HV244": "HV244 - Own land usable for agriculture (Dueño de tierras agrícolas)",
    "hv244": "HV244 - Own land usable for agriculture (Dueño de tierras agrícolas)",
    "HV245": "HV245 - Hectares for agricultural land (Hectáreas de tierras agrícolas)",
    "hv245": "HV245 - Hectares for agricultural land (Hectáreas de tierras agrícolas)",
    "HV246": "HV246 - Livestock, herds or farm animals (Dueño de ganado/animales)",
    "hv246": "HV246 - Livestock, herds or farm animals (Dueño de ganado/animales)",
    "HV246A": "HV246A - Cattle own (Cantidad de ganado)",
    "hv246a": "HV246A - Cattle own (Cantidad de ganado)",
    "HV246C": "HV246C - Horses, donkeys, mules own (Cantidad de caballos, burros, mulas)",
    "hv246c": "HV246C - Horses, donkeys, mules own (Cantidad de caballos, burros, mulas)",
    "HV246D": "HV246D - Goats own (Cantidad de cabras)",
    "hv246d": "HV246D - Goats own (Cantidad de cabras)",
    "HV246E": "HV246E - Sheep own (Cantidad de ovejas)",
    "hv246e": "HV246E - Sheep own (Cantidad de ovejas)",
    "HV246G": "HV246G - Poultry own (Cantidad de aves de corral)",
    "hv246g": "HV246G - Poultry own (Cantidad de aves de corral)",
    "HV246H": "HV246H - Cuyes/rabits own (Cantidad de cuyes/conejos)",
    "hv246h": "HV246H - Cuyes/rabits own (Cantidad de cuyes/conejos)",
    "HV246I": "HV246I - Pigs own (Cantidad de cerdos)",
    "hv246i": "HV246I - Pigs own (Cantidad de cerdos)",
    "HV246J": "HV246J - Other own (Cantidad de otros animales)",
    "hv246j": "HV246J - Other own (Cantidad de otros animales)",
    "SHREGION": "SHREGION - Región natural",
    "shregion": "SHREGION - Región natural",
    "SHPROVIN": "SHPROVIN - Province (Provincia)",
    "shprovin": "SHPROVIN - Province (Provincia)",
    "SHDISTRI": "SHDISTRI - District (Distrito)",
    "shdistri": "SHDISTRI - District (Distrito)",
    "SHTRIMES": "SHTRIMES - Data collection round number",
    "shtrimes": "SHTRIMES - Data collection round number",
    "HV218": "HV218 - Line number of head of househ. (Número de línea del jefe de hogar)",
    "hv218": "HV218 - Line number of head of househ. (Número de línea del jefe de hogar)",
    "SHSEMES": "SHSEMES - Data collection round number / Semestre",
    "shsemes": "SHSEMES - Data collection round number / Semestre",
    "HC56A": "HC56A - Nivel de hemoglobina ajustado por altitud",
    "hc56a": "HC56A - Nivel de hemoglobina ajustado por altitud",
    "HC57A": "HC57A - Nivel de anemia",
    "hc57a": "HC57A - Nivel de anemia",
    "HC0": "HC0 - Número de orden / Índice del listado",
    "hc0": "HC0 - Número de orden / Índice del listado",
    "HC1": "HC1 - Edad en meses",
    "hc1": "HC1 - Edad en meses",
    "HC2": "HC2 - Peso en kilogramos (1 dec.)",
    "hc2": "HC2 - Peso en kilogramos (1 dec.)",
    "HC3": "HC3 - Altura en centímetros (1 dec.)",
    "hc3": "HC3 - Altura en centímetros (1 dec.)",
    "HC4": "HC4 - Talla/Edad percentil",
    "hc4": "HC4 - Talla/Edad percentil",
    "HC5": "HC5 - Talla/Edad Desviación Estándar",
    "hc5": "HC5 - Talla/Edad Desviación Estándar",
    "HC6": "HC6 - Talla/Edad porcentaje de la mediana",
    "hc6": "HC6 - Talla/Edad porcentaje de la mediana",
    "HC7": "HC7 - Peso/Edad percentil",
    "hc7": "HC7 - Peso/Edad percentil",
    "HC8": "HC8 - Peso/Edad Desviación Estándar",
    "hc8": "HC8 - Peso/Edad Desviación Estándar",
    "HC9": "HC9 - Peso/Edad porcentaje de la mediana",
    "hc9": "HC9 - Peso/Edad porcentaje de la mediana",
    "HC10": "HC10 - Peso/Talla percentil",
    "hc10": "HC10 - Peso/Talla percentil",
    "HC11": "HC11 - Peso/Talla Desviación Estándar",
    "hc11": "HC11 - Peso/Talla Desviación Estándar",
    "HC12": "HC12 - Peso/Talla porcentaje de la mediana",
    "hc12": "HC12 - Peso/Talla porcentaje de la mediana",
    "HC16": "HC16 - Día de nacimiento del niño",
    "hc16": "HC16 - Día de nacimiento del niño",
    "HC19": "HC19 - Año de la medición",
    "hc19": "HC19 - Año de la medición",
    "HC27": "HC27 - Sexo",
    "hc27": "HC27 - Sexo",
    "HC30": "HC30 - Mes de nacimiento del niño",
    "hc30": "HC30 - Mes de nacimiento del niño",
    "HC31": "HC31 - Año de nacimiento del niño",
    "hc31": "HC31 - Año de nacimiento del niño",
    "HC32": "HC32 - Fecha de nacimiento (cmc)",
    "hc32": "HC32 - Fecha de nacimiento (cmc)",
    "HC33": "HC33 - Fecha de información completa",
    "hc33": "HC33 - Fecha de información completa",
    "HC51": "HC51 - Número de orden del padre o responsable",
    "hc51": "HC51 - Número de orden del padre o responsable",
    "HC52": "HC52 - Leyó la declaración de consentimiento",
    "hc52": "HC52 - Leyó la declaración de consentimiento",
    "HC53": "HC53 - Nivel de hemoglobina (g/dl-1 decimal)",
    "hc53": "HC53 - Nivel de hemoglobina (g/dl-1 decimal)",
    "HC55": "HC55 - Resultado de medir (hemoglobina)",
    "hc55": "HC55 - Resultado de medir (hemoglobina)",
    "HC56": "HC56 - Nivel de hemoglobina ajustado por altitud",
    "hc56": "HC56 - Nivel de hemoglobina ajustado por altitud",
    "HC57": "HC57 - Nivel de anemia",
    "hc57": "HC57 - Nivel de anemia",
    "HC60": "HC60 - Número de línea de la madre en el hogar",
    "hc60": "HC60 - Número de línea de la madre en el hogar",
    "HC61": "HC61 - Nivel educativo más alto de la madre",
    "hc61": "HC61 - Nivel educativo más alto de la madre",
    "HC62": "HC62 - Año más alto de educación de la madre",
    "hc62": "HC62 - Año más alto de educación de la madre",
    "HC63": "HC63 - Intervalo de nacimientos anteriores al niño",
    "hc63": "HC63 - Intervalo de nacimientos anteriores al niño",
    "HC64": "HC64 - Número de orden de nacimiento",
    "hc64": "HC64 - Número de orden de nacimiento",
    "HC68": "HC68 - Nivel educativo más alto (para informe final)",
    "hc68": "HC68 - Nivel educativo más alto (para informe final)",
    "HC70": "HC70 - Talla/Edad Desviación Estándar (OMS)",
    "hc70": "HC70 - Talla/Edad Desviación Estándar (OMS)",
    "HC71": "HC71 - Peso/Edad Desviación Estándar (OMS)",
    "hc71": "HC71 - Peso/Edad Desviación Estándar (OMS)",
    "HC72": "HC72 - Peso/Talla Desviación Estándar (OMS)",
    "hc72": "HC72 - Peso/Talla Desviación Estándar (OMS)",
    "HC73": "HC73 - Desviación Estándar del IMC (OMS)",
    "hc73": "HC73 - Desviación Estándar del IMC (OMS)",
    "HC13": "HC13 - Razón por la cual el niño no se midió",
    "hc13": "HC13 - Razón por la cual el niño no se midió",
    "HC15": "HC15 - El niño se midió acostado o de pie",
    "hc15": "HC15 - El niño se midió acostado o de pie"
}
